In [1]:
# 1. Import Libraries
import pandas as pd
import numpy as np

In [2]:
# Load the iris dataset
df = pd.read_csv('iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
grouped_stats = df.groupby('Species').agg({
    'SepalLengthCm': ['mean', 'median', 'min', 'max', 'std'],
    'SepalWidthCm': ['mean', 'median', 'min', 'max', 'std'],
    'PetalLengthCm': ['mean', 'median', 'min', 'max', 'std'],
    'PetalWidthCm': ['mean', 'median', 'min', 'max', 'std'],
})

grouped_stats

                SepalLengthCm                            SepalWidthCm         \
                         mean median  min  max       std         mean median
Species
Iris-setosa             5.006    5.0  4.3  5.8  0.352490        3.418    3.4
Iris-versicolor         5.936    5.9  4.9  7.0  0.516171        2.770    2.8
Iris-virginica          6.588    6.5  4.9  7.9  0.635880        2.974    3.0

                                    PetalLengthCm                             \
                 min  max       std          mean median  min  max       std
Species
Iris-setosa      2.3  4.4  0.381024         1.464   1.50  1.0  1.9  0.173511
Iris-versicolor  2.0  3.4  0.313798         4.260   4.35  3.0  5.1  0.469911
Iris-virginica   2.2  3.8  0.322497         5.552   5.55  4.5  6.9  0.551895

                PetalWidthCm
                        mean median  min  max       std
Species
Iris-setosa            0.244    0.2  0.1  0.6  0.107210
Iris-versicolor        1.326    1.3  1.0  1.8  0.197753
Iris-virginica         2.026    2.0  1.4  2.5  0.274650

In [10]:
# Convert 'species' to numeric values
species_map = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
df['species_num'] = df['Species'].map(species_map)

# List containing numeric values for each response
species_numeric_list = df['species_num'].tolist()
print("Numeric list for species:", species_numeric_list[:10])  # print first 10 as sample

KeyError: 'species'